#!/usr/bin/env python3
"""
Extracts every code edit made in the in-scope HOBS app chats, verbatim, into
docs/history/code/<YYYY-MM>.md -- one entry per edit, in time order.

Verbatim means: the exact old/new text (or full file text) as it appeared in the
chat's tool call, with ONLY credentials redacted (see redact.py). Nothing is
paraphrased or retyped. Each entry records whether the edit actually applied
(the tool's own result), so a failed edit is never mistaken for a real change.

Limits, stated plainly:
- Only edits made through file-editing tools are captured. Changes made by shell
  commands (sed, python writes, heredocs) appear in the reading timeline as the
  command itself, not as a before/after diff.
- Edits made to artifacts in the claude.ai UI (not via tools) are not in the export.

Usage:
  python3 extract_code_edits.py <conversations.json> <repo_docs_history_code_dir>
"""
import json, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from redact import redact
from build_timeline import IN_SCOPE, CODE_TOOLS, edit_id


def fence(s):
    longest = max([len(m) for m in re.findall(r"`+", s)] + [0])
    return "`" * max(3, longest + 1)


def block(label, s):
    s = redact(s or "")
    f = fence(s)
    return f"{label}:\n{f}\n{s}\n{f}\n"


def main():
    src, outdir = sys.argv[1], sys.argv[2]
    os.makedirs(outdir, exist_ok=True)
    data = json.load(open(src))
    entries = []
    for c in data:
        label = next((v for k, v in IN_SCOPE.items() if c["uuid"].startswith(k)), None)
        if not label:
            continue
        for m in c.get("chat_messages") or []:
            blocks = m.get("content") or []
            results = {b.get("tool_use_id"): b for b in blocks if b.get("type") == "tool_result"}
            last_text = ""
            for i, b in enumerate(blocks):
                if b.get("type") == "text":
                    last_text = b.get("text", "")
                if b.get("type") != "tool_use" or b.get("name") not in CODE_TOOLS:
                    continue
                inp = b.get("input") or {}
                res = results.get(b.get("id"))
                if res is None:
                    status = "unknown (no result recorded)"
                else:
                    rtext = " ".join(x.get("text", "") for x in (res.get("content") or []) if isinstance(x, dict))
                    status = ("ERROR -- did NOT apply: " + redact(rtext[:300])) if res.get("is_error") else "applied"
                ts = b.get("start_timestamp") or m.get("created_at") or ""
                entries.append((ts, m.get("uuid", ""), i, label, b.get("name"), inp, status, last_text))
    entries.sort(key=lambda e: (e[0], e[1], e[2]))

    by_month = {}
    for ts, muuid, i, label, name, inp, status, why in entries:
        eid = edit_id(muuid, i)
        path = inp.get("path") or inp.get("file_path") or "(no path)"
        out = [f"### {eid}", f"- when: {ts}", f"- chat: {label}", f"- tool: {name}",
               f"- file: `{path}`", f"- result: {status}"]
        if why.strip():
            w = redact(why.strip().replace("\n", " "))
            out.append(f"- Claude's words just before this edit: \"{w[:400]}{'...' if len(w) > 400 else ''}\"")
        out.append("")
        if name in ("str_replace", "Edit"):
            out.append(block("OLD (exact)", inp.get("old_str", inp.get("old_string", ""))))
            out.append(block("NEW (exact)", inp.get("new_str", inp.get("new_string", ""))))
        elif name == "MultiEdit":
            for j, e in enumerate(inp.get("edits") or []):
                out.append(block(f"OLD #{j+1} (exact)", e.get("old_string", "")))
                out.append(block(f"NEW #{j+1} (exact)", e.get("new_string", "")))
        else:
            out.append(block("FULL FILE TEXT (exact)", inp.get("file_text", inp.get("content", ""))))
        by_month.setdefault(ts[:7] or "unknown", []).append("\n".join(out))

    for month, items in sorted(by_month.items()):
        header = (f"# Code edits recovered verbatim from chats -- {month}\n\n"
                  "Generated by `tools/history/extract_code_edits.py` from the claude.ai export. "
                  "Exact text as it appeared in each edit, credentials redacted only. "
                  "See the script's header for what this does and does not capture.\n\n"
                  f"Entries this month: {len(items)}\n\n---\n\n")
        open(os.path.join(outdir, f"{month}.md"), "w").write(header + "\n\n---\n\n".join(items) + "\n")
    print(f"edits: {len(entries)}  months: {sorted(by_month)}")
    print("failed edits:", sum(1 for e in entries if e[6].startswith("ERROR")))


if __name__ == "__main__":
    main()
